//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoria
    {
        public categoria()
        {
            this.productoes = new HashSet<producto>();
        }
    
        public int id { get; set; }
        public string nombre_categoria { get; set; }
        public int grupo_id { get; set; }
    
        public virtual ICollection<producto> productoes { get; set; }
        public virtual grupo grupo { get; set; }
    }
}
