//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class shoemarketEntities : DbContext
    {
        public shoemarketEntities()
            : base("name=shoemarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categorias { get; set; }
        public DbSet<direccion> direccions { get; set; }
        public DbSet<grupo> grupoes { get; set; }
        public DbSet<metodo_de_pago> metodo_de_pago { get; set; }
        public DbSet<orden> ordens { get; set; }
        public DbSet<orden_detalle> orden_detalle { get; set; }
        public DbSet<producto> productoes { get; set; }
        public DbSet<rol> rols { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<usuario> usuarios { get; set; }
    }
}
