//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int pago_id { get; set; }
        public int usuario_id { get; set; }
        public int orden_detalle_id { get; set; }
    
        public virtual metodo_de_pago metodo_de_pago { get; set; }
        public virtual orden_detalle orden_detalle { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
