//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class orden_detalle
    {
        public orden_detalle()
        {
            this.ordens = new HashSet<orden>();
        }
    
        public int id { get; set; }
        public int cantidad { get; set; }
        public double precioProducto { get; set; }
        public int producto_id { get; set; }
    
        public virtual ICollection<orden> ordens { get; set; }
        public virtual producto producto { get; set; }
    }
}
