//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoeMarket
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public producto()
        {
            this.orden_detalle = new HashSet<orden_detalle>();
            this.usuarios = new HashSet<usuario>();
        }
    
        public int id { get; set; }
        public string nombre_producto { get; set; }
        public string imagen { get; set; }
        public string descripcion { get; set; }
        public decimal precio { get; set; }
        public int stock { get; set; }
        public int categoria_id { get; set; }
    
        public virtual categoria categoria { get; set; }
        public virtual ICollection<orden_detalle> orden_detalle { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
    }
}
